development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: whatsapp_chat_reader_development
  pool: 5
  username: root
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: whatsapp_chat_reader_test
  pool: 5
  username: root
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: whatsapp_chat_reader_production
  pool: 5
  username: root
  host: localhost